In [ ]:
# Import the TensorFlow library and give it a short nickname 'tf'
import tensorflow as tf

# Print the currently installed version of TensorFlow
print("TensorFlow vresion :", tf.__version__)

TensorFlow vresion : 2.20.0


In [ ]:
# Check for GPUs is available
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [ ]:
# Import the numpy library and give it a short nickname 'np'
import numpy as np

## Create Tensor..

In [ ]:
# Create a constant tensor and store the value 10 in it
x = tf.constant(10)
x

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
# Create a contant tensor with a decimal number (floating-point)
y = tf.constant(10.5)
y

<tf.Tensor: shape=(), dtype=float32, numpy=10.5>

In [ ]:
# Create a constant tensor containing text data (string)
z = tf.constant("India")
z

<tf.Tensor: shape=(), dtype=string, numpy=b'India'>

In [ ]:
# Create a 1-Dimensional constant tensor (Vector) using a Python list
s = tf.constant([1 ,2, 3, 4, 5, 6])
s

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [ ]:
# Create a 2-Dimensional array (Matrix) with 2 rows and 3 columns
a = np.array([[1, 2, 3],[4, 5, 6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [ ]:
# Create a 1-Dimensional constant tensor (Vector) with 4 items
d_1 = tf.constant([1,2,3,4])
d_1

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Create a 2-Dimensional constant tensor (Matrix) with 2 rows and 3 columns
d_2 = tf.constant([[1,2,3],[4,5,6]])
d_2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# Provide a flat list of 4 numbers and force it to reshape into a 2x2 matrix
d_1_to_2 = tf.constant([1,2,3,4], shape=(2,2),dtype="int32")
d_1_to_2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Create a 3-Dimensional constant tensor using 3 nested brackets
d_3 = tf.constant([[[1,2],[3,4],[5,6]]],dtype="float32")
d_3

<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.],
        [5., 6.]]], dtype=float32)>

In [ ]:
# Check the exact Python class/data type of the variable 'd_3'
type(d_3)

tensorflow.python.framework.ops.EagerTensor

In [ ]:
# Check the dimensions (shape) of the 3D tensor 'd_3'
d_3.shape

TensorShape([1, 3, 2])

## TensorFlow Variable..

In [ ]:
# Create a variable tensor containing the number 1 (It is not a fix value, we are changed it)
tf.Variable(1)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [ ]:
# Create a 1-Dimensional variable tensor (Vector) containing a list of 4 numbers
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Check the internal name assigned to the variable 'x' by TensorFlow
x.name

'x:0'

In [ ]:
# Check the dimensions (size) of the variable 'x'
x.shape

TensorShape([4])

In [ ]:
# Check the data type of the numbers stored inside 'x'
x.dtype

tf.int32

In [ ]:
# Create a 1D variable tensor with a mix of float and integer values
y = tf.Variable([1.0,2,3,3.3,4])
y

<tf.Variable 'Variable:0' shape=(5,) dtype=float32, numpy=array([1. , 2. , 3. , 3.3, 4. ], dtype=float32)>

In [ ]:
# Create a variable with value True, and set its 'trainable' property to False
z = tf.Variable(True, False)
z

<tf.Variable 'Variable:0' shape=() dtype=bool, numpy=True>

In [ ]:
# Create a 1-Dimensional constant tensor (Vector) containing 4 items
t_con = tf.constant([1,2,3,4])
t_con

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Create a new Variable by passing an already existing constant tensor (t_con)
tf.Variable(t_con)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

## Creating TensorFlow variable with different shape..

In [ ]:
# Create a 2-Dimensional variable tensor (Matrix) with 2 rows and 2 columns
t_2d = tf.Variable([[2,3],[4,5]])
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
# Reshape the existing 1D variable 'x' into a 2D matrix
tf.reshape(x,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# Find the index (position) of the largest value in the 2D tensor 't_2d'
t_2d

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.argmax(t_2d)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

In [ ]:
# Convert the 2D variable 't_2d' back into an immutable (constant) tensor
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
tf.convert_to_tensor(t_2d)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
# Update the contents of the existing variable 'x' with a new list of numbers
x = tf.Variable([1,2,3,4])
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [ ]:
x.assign([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 8], dtype=int32)>

In [ ]:
x.assign([4,6,2,9])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([4, 6, 2, 9], dtype=int32)>

In [ ]:
# Add new values to the existing values of variable 'x'
x.assign_add([4,6,2,8])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

In [ ]:
x

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([ 8, 12,  4, 17], dtype=int32)>

## Tensor Math Modules..

In [ ]:
# Create two variables
a = 10
b = 20

In [ ]:
# Add 'a' and 'b'
a + b

30

In [ ]:
# Add tensor 'a' and tensor 'b' together
tf.add(a,b)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [ ]:
# Addition of two list
l1 = [1,2,3,4]
l2 = [5,6,7,8]

tf.add(l1,l2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
# Addition of two tuple
t1 = (1,2,3,4)
t2 = (5,6,7,8)

tf.add(t1,t2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 6,  8, 10, 12], dtype=int32)>

In [ ]:
l1 = [1,2,3,4]
a = 10

tf.add(l1,a)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([11, 12, 13, 14], dtype=int32)>

In [ ]:
# Given a tensor x and tensor y, this operation x^y computes for corresponding elements in x and y
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# tf.math.abs

# Real number
x = tf.constant([-2.25,3.25])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
# Complex number
x = tf.constant([[-2.25 + 4.75j],[-3.25 + 5.75j]])
tf.abs(x)

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[5.25594901],
       [6.60492241]])>

In [ ]:
# tf.math.subtract
x = [1,2,3,4,5]
y = 1
tf.subtract(x,y)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [ ]:
# tf.math.multiply
x = tf.constant([1,2,3,4])
tf.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
tf.math.multiply(x,x)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  4,  9, 16], dtype=int32)>

In [ ]:
x = tf.ones([1,2]);
y = tf.ones([2,1]);

x * y

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
# tf.math.maximum
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-2, 0., 2., 5.])

tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
tf.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>

In [ ]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])
tf.math.maximum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-3.,  0.,  0.,  0.], dtype=float32)>

In [ ]:
# tf.math.minimum
x = tf.constant([0., 0., 0., 0.])
y = tf.constant([-5., -2., 0., 3.])

tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -2.,  0.,  0.], dtype=float32)>

In [ ]:
x = tf.constant([-5., 0., 0., 0.])
y = tf.constant([-3.])

tf.math.minimum(x,y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([-5., -3., -3., -3.], dtype=float32)>

In [ ]:
# tf.math.log
x = tf.constant([0, 0.5, 1, 5])

tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [ ]:
# tf.math.divide
x = tf.constant([16, 12, 11])
y = tf.constant([4, 6, 2])

tf.math.divide(x,y)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([4. , 2. , 5.5])>

In [ ]:
# tf.math.pow
x = tf.constant([[2,2],[3,3]])
y = tf.constant([[8,16],[2,3]])

tf.math.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [ ]:
# tf.math.sqrt
x = tf.constant([[4.0],[16.0]])

tf.math.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [ ]:
y = tf.constant([[-4.0],[16.0]])

tf.math.sqrt(y)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[nan],
       [ 4.]], dtype=float32)>

In [ ]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [ ]:
tf.ones((1)),tf.float32

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 tf.float32)

In [ ]:
ones_d2 = tf.ones((2,2)),tf.float32
ones_d2

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 tf.float32)

In [ ]:
ones_3d = tf.ones((2,2,3),tf.float32)
ones_3d

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [ ]:
# Ones_like: Creates a tensor of all ones that has the same shape as the input.
tensor = tf.constant([[1,2,3],[4,5,6]])
tf.ones_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
tensor = tf.constant([[1,2,3],[4,5,6]])
tf.zeros_like(tensor)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## **Placeholder -** Migrate tensorflow 1 code to tensorflow 2

Placeholder is a variable that we will assign data to at a later date.

In [ ]:
# Turn off the modern line-by-line execution (Eager Execution) of TensorFlow 2.x
tf.compat.v1.disable_eager_execution()

In [ ]:
# Create an empty placeholder (a promise to provide data later)
tf.compat.v1.placeholder(dtype = tf.float32, shape=(400,400))

<tf.Tensor 'Placeholder:0' shape=(400, 400) dtype=float32>

In [ ]:
# Create a placeholder blueprint and store it in variable 'a'
a = tf.compat.v1.placeholder(dtype = tf.float32, shape = (400,400))
a

<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [ ]:
# Create a placeholder blueprint and store it in variable 'b'
b = tf.compat.v1.placeholder(dtype=tf.float32, shape=(400,400))
b

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

In [ ]:
# Define the addition operation between 'a' and 'b'
c = tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

In [ ]:
# Create a 400x400 matrix filled entirely with the number 1.0
ones_array = np.ones((400,400), np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [ ]:
# Start the TensorFlow execution engine (Session)
with tf.compat.v1.Session() as sess:
  # Run the operation 'c' (which was a + b) and feed the actual data into the placeholders
  d = sess.run(c, feed_dict = {a:ones_array, b:ones_array})

In [ ]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

## Sparse Tensors
It enables efficient storage & processing of tensors that contains lot of zero values

In [ ]:
# Create a SparseTensor representing a 3x10 matrix where most values are zero
tf.SparseTensor(indices = [[0,3],[2,4]], values = [10,20], dense_shape = [3,10])

SparseTensor(indices=Tensor("SparseTensor/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor/dense_shape:0", shape=(2,), dtype=int64))

In [ ]:
# Create a SparseTensor and assign it to the variable 'st1'
st1 = tf.SparseTensor(indices=[[0,3],[2,4]], values=[10,20], dense_shape=[3,10])
st1

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))

In [ ]:
print(st1)

SparseTensor(indices=Tensor("SparseTensor_1/indices:0", shape=(2, 2), dtype=int64), values=Tensor("SparseTensor_1/values:0", shape=(2,), dtype=int32), dense_shape=Tensor("SparseTensor_1/dense_shape:0", shape=(2,), dtype=int64))


In [ ]:
# Create or retrieve a variable named "x" in the TensorFlow graph
# We explicitly set its type to 32-bit integer and initialize it with the value [5]
x = tf.compat.v1.get_variable("x", dtype=tf.int32, initializer=tf.constant([5]))

# Create or retrieve another variable named "y"
# Initialized with the value [6]
y = tf.compat.v1.get_variable("y", dtype=tf.int32, initializer=tf.constant([6]))

In [ ]:
# Create two constants and assign them specific names in the computational graph
# 'name' parameter helps in tracking these nodes if we visualize the graph later
c = tf.constant([5], name = "constant")
square = tf.constant([2], name = "square")

# Define the mathematical equation: f = (x * y) + x^2 + y + c
# The operations are added to the TensorFlow blueprint, but not calculated yet
f = tf.multiply(x,y) + tf.pow(x, square) + y + c

f

<tf.Tensor 'add_3:0' shape=(1,) dtype=int32>

### Output Observation :
- **No Calculation Yet:** Because Eager Execution is turned off, the engine has only connected all the mathematical steps into a chain (graph), but has not yet flowed the actual values ​​inside the variables x and y.

- **How to execute this? :** To get the actual number 66 from Is f, you will need to start a Session. But a new rule applies here: variables, like placeholders, are not automatically ready to run. Just before running the session you need to turn on a master switch in the graph called tf.compat.v1.global_variables_initializer(), only then will x and y release their initial values ​​(5 and 6) in memory.